### ISSUE TITLE
Adding your component breaks the build

### ISSUE THREAD

**Issue by McPringle** [mcollovati/vaadin-twitter-widgets#13]
```
java.lang.IllegalStateException: Running project in development mode with no access to folder
'/home/marco/projects/marco/vaadin-twitter-widgets/twitter-widgets-addon'.
```

Looks like there is a hard-coded directory from your local drive...

**Comment by mcollovati** [comment]
Hi, thank you very much for reporting.
There's a generated file `META-INF/VAADIN/config/flow-build-info.json` that shouldn't be included in the final artifact.
I'll fix this a soon as possible and publish a new release.

**Comment by McPringle** [comment]
Yes, that could be the reason. Your package is missing an `s`:

```
  package org.vaadin.addon.twitter;  // is
  package org.vaadin.addons.twitter; // should
```

**Comment by mcollovati** [comment]
Not, only the `s`. Actual group id also misses component name.

So I think I should move to new coordinates: from `org.vaadin.addon:twitter-widgets` to `org.vaadin.addon.twitterwidgets:twitter-widgets`

**Comment by McPringle** [comment]
Don't forget the `s` in the group id either! :-)

**Comment by mcollovati** [comment]
Finally, thanks to Vaadin team help, I got the fix published also on maven repository.
Version is 2.1.1, maven coordinates are the same as before: `org.vaadin.addon:twitter-widgets`

@McPringle feel free to reopen this issue if still not working (or to open other issues if you find other bugs :wink:  )
